import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black overflow-hidden z-10 w-full min-h-screen`}
      >
        <SessionProvider>

          <Navbar /> 
          {/* h-16 h navbar ki */}
          <div className="relative flex items-center h-[calc(100vh-4rem)]">
            <div className="absolute inset-0 opacity-20 z-[-10]">
              <div className="absolute w-[40rem] h-[40rem] bg-purple-500 rounded-full blur-3xl -top-48 -left-48 animate-pulse" />
              <div className="absolute w-[40rem] h-[40rem] bg-blue-500 rounded-full blur-3xl -bottom-48 -right-48 animate-pulse" />
            </div>
            {children}  
         </div>
        </SessionProvider>

      </body>
    </html>
  );
}
